name: sticky
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.4.6
  google_fonts: ^3.0.1
  swipable_stack: ^2.0.0
  graphql_flutter: ^5.1.0
  profile: ^0.0.1
  firebase_core: ^1.22.0
  visibility_detector: ^0.3.3
  font_awesome_flutter: ^10.2.1
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.6
  get: ^4.6.5

dev_dependencies:
  icons_launcher: ^2.0.5
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#000000"
  image: icons/splash.png

icons_launcher:
  image_path: 'icons/icon.png'
  platforms:
    android:
      enable: true
      image_path: 'icons/icon.png'
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: 'icons/background.png'
      adaptive_foreground_image: 'icons/foreground.png'
      adaptive_round_image: 'icons/round.png'
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    
  